<Project Sdk="Aspire.AppHost.Sdk/13.4.6">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>apphost-e39e007b27ea477dfdc2a9ae451d09769cbaea2709436630b62461add54062d8</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Tomlyn" Version="2.10.1" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Portfolio.Orchestrator.Tests" />
  </ItemGroup>

</Project>
